### ISSUE TITLE
Trouble with console_script from extra rest-service when installing from PyPI

### ISSUE THREAD

**Issue by funkyfuture** [telota/rasmipy#9]
while an installation from the local sources works:

```
$ pip install .[rest-service]
Processing /home/user/dev/rasmipy
Requirement already satisfied: hug in /home/user/.local/share/virtualenvs/eb8f09718840560/lib/python3.5/site-packages (from rasmipy==0.2.1)
Requirement already satisfied: requests in /home/user/.local/share/virtualenvs/eb8f09718840560/lib/python3.5/site-packages (from hug->rasmipy==0.2.1)
Requirement already satisfied: falcon==1.2.0 in /home/user/.local/share/virtualenvs/eb8f09718840560/lib/python3.5/site-packages (from hug->rasmipy==0.2.1)
Requirement already satisfied: six>=1.4.0 in /home/user/.local/share/virtualenvs/eb8f09718840560/lib/python3.5/site-packages (from falcon==1.2.0->hug->rasmipy==0.2.1)
Requirement already satisfied: python-mimeparse>=1.5.2 in /home/user/.local/share/virtualenvs/eb8f09718840560/lib/python3.5/site-packages (from falcon==1.2.0->hug->rasmipy==0.2.1)
Installing collected packages: rasmipy
  Found existing installation: rasmipy 0.2
    Uninstalling rasmipy-0.2:
      Successfully uninstalled rasmipy-0.2
  Running setup.py install for rasmipy ... done
Successfully installed rasmipy-0.2.1

```

there's an issue with an installation from the PyPI:

```
$ pip install rasmipy[rest-api]
Collecting rasmipy[rest-api]
  Downloading rasmipy-0.2.tar.gz
Collecting hug (from rasmipy[rest-api])
Collecting falcon==1.2.0 (from hug->rasmipy[rest-api])
  Using cached falcon-1.2.0-py2.py3-none-any.whl
Collecting requests (from hug->rasmipy[rest-api])
  Using cached requests-2.13.0-py2.py3-none-any.whl
Requirement already satisfied: six>=1.4.0 in /home/user/.local/share/virtualenvs/eb8f09718840560/lib/python3.5/site-packages (from falcon==1.2.0->hug->rasmipy[rest-api])
Collecting python-mimeparse>=1.5.2 (from falcon==1.2.0->hug->rasmipy[rest-api])
  Using cached python_mimeparse-1.6.0-py2.py3-none-any.whl
Building wheels for collected packages: rasmipy
  Running setup.py bdist_wheel for rasmipy ... done
  Stored in directory: /home/user/.cache/pip/wheels/98/f5/f3/51e6a58ab3ecb33bf35eba10f70889e86d08bf4fb8514430a2
Successfully built rasmipy
Installing collected packages: python-mimeparse, falcon, requests, hug, rasmipy
Exception:
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/eb8f09718840560/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/user/.local/share/virtualenvs/eb8f09718840560/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/user/.local/share/virtualenvs/eb8f09718840560/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/user/.local/share/virtualenvs/eb8f09718840560/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/user/.local/share/virtualenvs/eb8f09718840560/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/user/.local/share/virtualenvs/eb8f09718840560/lib/python3.5/site-packages/pip/wheel.py", line 492, in move_wheel_files
    maker.make_multiple(['%s = %s' % kv for kv in console.items()])
  File "/home/user/.local/share/virtualenvs/eb8f09718840560/lib/python3.5/site-packages/pip/_vendor/distlib/scripts.py", line 383, in make_multiple
    filenames.extend(self.make(specification, options))
  File "/home/user/.local/share/virtualenvs/eb8f09718840560/lib/python3.5/site-packages/pip/_vendor/distlib/scripts.py", line 368, in make
    entry = get_export_entry(specification)
  File "/home/user/.local/share/virtualenvs/eb8f09718840560/lib/python3.5/site-packages/pip/_vendor/distlib/util.py", line 590, in get_export_entry
    "'%s'" % specification)
pip._vendor.distlib.DistlibException: Invalid specification 'rasmify-rest-service = rasmipy.rest_service:serve [rest-api]'
```

the only difference between `0.2` (on PyPI / below) and `0.2.1` (the sources / above) is that `rest-api` was renamed to `rest-service`.

**Comment by funkyfuture** [comment]
i'm getting some quirky behaviour under certain circumstances when trying to reproduce this.

@suchmaske let's release `0.2.1` on the PyPI and see what happens. it makes more sense to write a bug report where sources and repo package are identical. the extra dependency is broken anyway..

**Comment by suchmaske** [comment]
@funkyfuture Just roll out an update an hope it works?
